"""initial schema

Revision ID: d69d39b0e251
Revises:
Create Date: 2025-12-28 01:27:49.086557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
import os

# Add parent directory to path for UUID import
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from src.models import UUID


# revision identifiers, used by Alembic.
revision: str = 'd69d39b0e251'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_groups',
    sa.Column('group_id', UUID(), nullable=False),
    sa.Column('duplicate_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('duplicate_members',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('group_id', UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=16), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('ix_duplicate_member_group', 'duplicate_members', ['group_id'], unique=False)
    op.create_index('ix_duplicate_member_hash', 'duplicate_members', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_duplicate_member_hash', table_name='duplicate_members')
    op.drop_index('ix_duplicate_member_group', table_name='duplicate_members')
    op.drop_table('duplicate_members')
    op.drop_table('duplicate_groups')
    # ### end Alembic commands ###
