"""initial schema

Revision ID: 4a1bae51c58e
Revises:
Create Date: 2025-12-28 01:04:39.684663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
import os

# Add parent directory to path for UUID import
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from src.models import UUID


# revision identifiers, used by Alembic.
revision: str = '4a1bae51c58e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_groups',
    sa.Column('group_id', UUID(), nullable=False),
    sa.Column('group_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_members',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('group_id', UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['file_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('ix_group_member_group_primary', 'group_members', ['group_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_group_members_file_type'), 'group_members', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_members_file_type'), table_name='group_members')
    op.drop_index('ix_group_member_group_primary', table_name='group_members')
    op.drop_table('group_members')
    op.drop_table('file_groups')
    # ### end Alembic commands ###
